language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
<<<<<<< HEAD
  - yarn global add codecov
=======
  - yarn add -g codecov
>>>>>>> cecd535248e2c8eb031932469a71974201b4f79b

jobs:
  include:
    - stage: Produce Coverage
      script: jest --config=jest.config.json --coverage && codecov
